import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

// Original synthetic fixtures for exercising features, not a validated curriculum.
// title, transcript, English meaning, grammar, writing prompt, cloze, accepted answer
const data = {
  fr: [
    ['Meeting a colleague', 'Bonjour, je suis Camille. Je travaille avec votre équipe. Et vous, quel est votre rôle ?', 'Hello, I am Camille. I work with your team. And you, what is your role?', 'Je suis introduces identity; je travaille describes an activity. Vous is the polite or plural form.', 'Introduce yourself and describe your role.', 'Je ___ Camille.', 'suis'],
    ['Planning the morning', 'Le matin, je bois un café et je lis mes messages. Ensuite, je commence mon travail.', 'In the morning, I drink a coffee and read my messages. Then I start my work.', 'Use the present tense for routines. Ensuite connects the next activity.', 'Write two sentences about your morning.', 'Ensuite, je ___ mon travail.', 'commence'],
    ['At the café', 'Je voudrais un thé, s’il vous plaît. Est-ce que cette table est libre ? Merci beaucoup.', 'I would like a tea, please. Is this table free? Thank you very much.', 'Je voudrais makes a polite request. Est-ce que introduces a question.', 'Ask politely for a drink and a place to sit.', 'Je ___ un thé.', 'voudrais'],
    ['Changing a meeting', 'La réunion est à dix heures. Je ne suis pas disponible. Est-ce que nous pouvons la déplacer à onze heures ?', 'The meeting is at ten. I am not available. Can we move it to eleven?', 'Ne … pas surrounds the verb to express negation. À introduces a clock time.', 'Explain that you need to change a meeting time.', 'Je ne suis ___ disponible.', 'pas'],
    ['Getting around', 'Je vais à la gare en bus. Le trajet dure vingt minutes. Où est l’arrêt le plus proche ?', 'I go to the station by bus. The journey takes twenty minutes. Where is the nearest stop?', 'Je vais describes going somewhere. Où asks about a place.', 'Describe how you travel to a familiar place.', '___ est l’arrêt ?', 'Où'],
    ['Buying groceries', 'Il me faut du pain et des pommes. Je prépare le dîner pour deux personnes. Combien coûtent les pommes ?', 'I need bread and apples. I am preparing dinner for two people. How much do the apples cost?', 'Du marks an unspecified amount; des introduces an unspecified plural quantity.', 'Write what you need for a meal.', 'Il me faut ___ pain.', 'du'],
    ['Sharing an interest', 'J’aime lire le soir. En ce moment, je lis un livre sur l’histoire. Qu’est-ce que vous aimez lire ?', 'I like reading in the evening. At the moment I am reading a book about history. What do you like to read?', 'Aimer followed by an infinitive expresses liking an activity.', 'Describe an interest and ask a related question.', 'J’aime ___ le soir.', 'lire'],
    ['Offering help', 'Vous avez beaucoup de travail aujourd’hui. Je peux vous aider après le déjeuner. Par quoi voulez-vous commencer ?', 'You have a lot of work today. I can help you after lunch. What would you like to start with?', 'Je peux followed by an infinitive expresses ability or an offer.', 'Offer help with a task.', 'Je ___ vous aider.', 'peux'],
    ['Expressing a preference', 'Je préfère travailler au calme. La musique me distrait parfois. Mais chacun a ses habitudes.', 'I prefer working in a quiet setting. Music sometimes distracts me. But everyone has their habits.', 'Préférer followed by an infinitive states a preference. Mais introduces a contrast.', 'Explain a preference respectfully.', 'Je ___ travailler au calme.', 'préfère'],
    ['Weekend plans', 'Ce week-end, je vais voir des amis. Nous allons cuisiner ensemble. Si le temps est beau, nous mangerons dehors.', 'This weekend I am going to see friends. We are going to cook together. If the weather is nice, we will eat outside.', 'Aller plus an infinitive expresses a plan. Nous mangerons is the future of manger.', 'Write about a weekend plan.', 'Nous ___ cuisiner ensemble.', 'allons'],
  ],
  tr: [
    ['Meeting a colleague', 'Merhaba, ben Deniz. Sizin ekibinizle çalışıyorum. Sizin göreviniz nedir?', 'Hello, I am Deniz. I work with your team. What is your role?', 'Ben means I. Çalışıyorum uses the -iyor present progressive pattern. Sizin is polite or plural your.', 'Introduce yourself and describe your role.', 'Merhaba, ___ Deniz.', 'ben'],
    ['Planning the morning', 'Sabah kahve içiyorum ve mesajlarımı okuyorum. Sonra çalışmaya başlıyorum.', 'In the morning I drink coffee and read my messages. Then I begin working.', 'Ve joins ideas. Sonra introduces the next activity.', 'Write two sentences about your morning.', 'Sabah kahve ___ .', 'içiyorum'],
    ['At the café', 'Bir çay istiyorum, lütfen. Bu masa boş mu? Çok teşekkür ederim.', 'I would like a tea, please. Is this table free? Thank you very much.', 'The question particle mı/mi/mu/mü is written separately and follows vowel harmony.', 'Ask for a drink and check whether a table is free.', 'Bu masa boş ___?', 'mu'],
    ['Changing a meeting', 'Toplantı saat onda. O saatte müsait değilim. Toplantıyı saat on bire alabilir miyiz?', 'The meeting is at ten. I am not available then. Can we move the meeting to eleven?', 'Değilim negates a first-person description. -abilir expresses possibility or ability.', 'Explain that you need to change a meeting time.', 'Müsait ___ .', 'değilim'],
    ['Getting around', 'İstasyona otobüsle gidiyorum. Yolculuk yirmi dakika sürüyor. En yakın durak nerede?', 'I go to the station by bus. The journey takes twenty minutes. Where is the nearest stop?', '-a/-e marks a destination; -la/-le can express by or with. Nerede means where.', 'Describe how you travel to a familiar place.', 'En yakın durak ___?', 'nerede'],
    ['Buying groceries', 'Ekmek ve elma almam gerekiyor. İki kişi için akşam yemeği hazırlıyorum. Elmaların kilosu ne kadar?', 'I need to buy bread and apples. I am preparing dinner for two people. How much is a kilo of apples?', 'Gerekiyor expresses a need. İçin means for.', 'Write what you need for a meal.', 'İki kişi ___ yemek hazırlıyorum.', 'için'],
    ['Sharing an interest', 'Akşamları kitap okumayı seviyorum. Şu anda tarih hakkında bir kitap okuyorum. Siz ne okumayı seversiniz?', 'I like reading books in the evenings. I am currently reading a book about history. What do you like to read?', 'Okumayı seviyorum expresses liking reading. Hakkında means about.', 'Describe an interest and ask a related question.', 'Kitap okumayı ___ .', 'seviyorum'],
    ['Offering help', 'Bugün çok işiniz var. Öğle yemeğinden sonra size yardım edebilirim. Nereden başlamak istersiniz?', 'You have a lot of work today. I can help you after lunch. Where would you like to start?', 'Size means to you. Yardım edebilirim is an offer: I can help.', 'Offer help with a task.', 'Size yardım ___ .', 'edebilirim'],
    ['Expressing a preference', 'Sessiz bir yerde çalışmayı tercih ediyorum. Müzik bazen dikkatimi dağıtıyor. Ama herkesin alışkanlıkları farklı.', 'I prefer working in a quiet place. Music sometimes distracts me. But everyone has different habits.', 'Tercih ediyorum expresses preference. Ama introduces a contrast.', 'Explain a preference respectfully.', '___ bir yerde çalışmayı tercih ediyorum.', 'Sessiz'],
    ['Weekend plans', 'Bu hafta sonu arkadaşlarımla buluşacağım. Birlikte yemek yapacağız. Hava güzel olursa dışarıda yiyeceğiz.', 'This weekend I will meet my friends. We will cook together. If the weather is nice, we will eat outside.', '-acak/-ecek forms the future tense. Birlikte means together.', 'Write about a weekend plan.', '___ yemek yapacağız.', 'Birlikte'],
  ],
  ru: [
    ['Meeting a colleague', 'Здравствуйте, меня зовут Саша. Я работаю с вашей командой. Чем вы занимаетесь?', 'Hello, my name is Sasha. I work with your team. What do you do?', 'Меня зовут introduces a name. Вы is polite or plural you. Russian usually omits am/is in the present.', 'Introduce yourself and describe your role.', 'Меня ___ Саша.', 'зовут'],
    ['Planning the morning', 'Утром я пью кофе и читаю сообщения. Потом я начинаю работать.', 'In the morning I drink coffee and read messages. Then I begin working.', 'Утром means in the morning. Потом connects the next activity.', 'Write two sentences about your morning.', 'Утром я ___ кофе.', 'пью'],
    ['At the café', 'Можно мне чай, пожалуйста? Этот стол свободен? Большое спасибо.', 'May I have tea, please? Is this table free? Thank you very much.', 'Можно мне is a useful polite request. Свободен describes a masculine singular subject.', 'Ask politely for a drink and a place to sit.', 'Можно мне чай, ___?', 'пожалуйста'],
    ['Changing a meeting', 'Встреча в десять часов. В это время я не могу. Можно перенести встречу на одиннадцать?', 'The meeting is at ten. I cannot make that time. Can we move the meeting to eleven?', 'Не before a verb negates it. В introduces a clock time; на is used here for a rescheduled time.', 'Explain that you need to change a meeting time.', 'Я ___ могу.', 'не'],
    ['Getting around', 'Я еду на вокзал на автобусе. Дорога занимает двадцать минут. Где ближайшая остановка?', 'I am going to the station by bus. The journey takes twenty minutes. Where is the nearest stop?', 'Еду describes travel by vehicle. На автобусе means by bus. Где asks where.', 'Describe how you travel to a familiar place.', '___ ближайшая остановка?', 'Где'],
    ['Buying groceries', 'Мне нужны хлеб и яблоки. Я готовлю ужин на двоих. Сколько стоят яблоки?', 'I need bread and apples. I am preparing dinner for two. How much do the apples cost?', 'Мне нужны expresses a need for plural items. Сколько asks how much or how many.', 'Write what you need for a meal.', 'Мне ___ хлеб и яблоки.', 'нужны'],
    ['Sharing an interest', 'Я люблю читать по вечерам. Сейчас я читаю книгу об истории. А что вы любите читать?', 'I like reading in the evenings. I am currently reading a book about history. What do you like to read?', 'Люблю plus an infinitive expresses liking an activity. Сейчас means now.', 'Describe an interest and ask a related question.', 'Я люблю ___ .', 'читать'],
    ['Offering help', 'У вас сегодня много работы. Я могу помочь вам после обеда. С чего вы хотите начать?', 'You have a lot of work today. I can help you after lunch. What would you like to start with?', 'Могу plus an infinitive expresses ability or an offer. После обеда means after lunch.', 'Offer help with a task.', 'Я могу ___ вам.', 'помочь'],
    ['Expressing a preference', 'Мне больше нравится работать в тишине. Музыка иногда меня отвлекает. Но у каждого свои привычки.', 'I prefer working in quiet. Music sometimes distracts me. But everyone has their own habits.', 'Мне нравится expresses liking; больше makes a comparison. Но introduces a contrast.', 'Explain a preference respectfully.', 'Мне больше ___ работать в тишине.', 'нравится'],
    ['Weekend plans', 'В эти выходные я встречусь с друзьями. Мы будем готовить вместе. Если будет хорошая погода, мы поедим на улице.', 'This weekend I will meet friends. We will cook together. If the weather is nice, we will eat outdoors.', 'Будем plus an infinitive forms an imperfective future. Встречусь and поедим are perfective future forms.', 'Write about a weekend plan.', 'Мы ___ готовить вместе.', 'будем'],
  ],
};

const lessons = [];
for (const [language, rows] of Object.entries(data)) {
  const languageLessons = rows.map(([title, transcript, meaning, grammar, prompt, cloze, answer], index) => {
    const id = `${language}-${String(index + 1).padStart(2, '0')}`;
    const directory = `apps/learning-app/public/test-lessons/audio/${language}`;
    mkdirSync(directory, { recursive: true });
    const output = `${directory}/${id}.wav`;
    const result = spawnSync('espeak-ng', ['-v', language, '-s', '145', '-w', output, '--stdin'], { input: transcript, encoding: 'utf8' });
    if (result.status !== 0) throw new Error(`Audio generation failed for ${id}: ${result.stderr}`);
    const bytes = readFileSync(output);
    if (bytes.toString('ascii', 0, 4) !== 'RIFF' || bytes.toString('ascii', 8, 12) !== 'WAVE' || bytes.length < 1000) throw new Error(`Invalid WAV: ${id}`);
    return { id, language, title, transcript, meaning, grammar, prompt, cloze, answer, audio: `/test-lessons/audio/${language}/${id}.wav`, fixture: true };
  });
  mkdirSync(`content/manifests/${language}`, { recursive: true });
  writeFileSync(`content/manifests/${language}/test-lessons.json`, JSON.stringify(languageLessons, null, 2) + '\n');
  lessons.push(...languageLessons);
}
writeFileSync('apps/learning-app/public/test-lessons/index.json', JSON.stringify({ version: 1, generator: 'eSpeak NG (synthetic test audio)', lessons }, null, 2) + '\n');
console.log(`Generated and validated ${lessons.length} original test lessons and WAV files.`);
