export const italianRows = [
  ['Meeting a colleague', 'Buongiorno, mi chiamo Luca. Lavoro con il vostro gruppo. Qual è il suo ruolo?', 'Good morning, my name is Luca. I work with your group. What is your role?', 'Mi chiamo introduces your name. Lavoro is the first-person present of lavorare. Suo is formal your here.', 'Introduce yourself and describe your role.', 'Mi ___ Luca.', 'chiamo'],
  ['Planning the morning', 'La mattina bevo un caffè e leggo i messaggi. Poi comincio a lavorare.', 'In the morning I drink a coffee and read messages. Then I begin working.', 'Bevo and leggo describe routines in the present. Poi means then.', 'Write two sentences about your morning.', 'La mattina ___ un caffè.', 'bevo'],
  ['At the café', 'Vorrei un tè, per favore. Questo tavolo è libero? Grazie mille.', 'I would like a tea, please. Is this table free? Thank you very much.', 'Vorrei is a polite way to say I would like. Libero agrees with the masculine singular tavolo.', 'Ask politely for a drink and a place to sit.', '___ un tè, per favore.', 'Vorrei'],
  ['Changing a meeting', 'La riunione è alle dieci. A quell’ora non posso. Possiamo spostarla alle undici?', 'The meeting is at ten. I cannot make that time. Can we move it to eleven?', 'Non before a verb makes it negative. Alle introduces a clock time. La in spostarla refers to the meeting.', 'Explain that you need to change a meeting time.', 'A quell’ora ___ posso.', 'non'],
  ['Getting around', 'Vado alla stazione in autobus. Il viaggio dura venti minuti. Dov’è la fermata più vicina?', 'I go to the station by bus. The journey takes twenty minutes. Where is the nearest stop?', 'Vado means I go. In autobus means by bus. Dov’è combines dove and è.', 'Describe how you travel to a familiar place.', 'Vado alla stazione ___ autobus.', 'in'],
  ['Buying groceries', 'Mi servono pane e mele. Preparo la cena per due persone. Quanto costano le mele?', 'I need bread and apples. I am preparing dinner for two people. How much do the apples cost?', 'Mi servono expresses a need for several items. Costano agrees with the plural mele.', 'Write what you need for a meal.', 'Quanto ___ le mele?', 'costano'],
  ['Sharing an interest', 'Mi piace leggere la sera. Adesso leggo un libro di storia. Che cosa le piace leggere?', 'I like reading in the evening. Now I am reading a history book. What do you like to read?', 'Mi piace followed by an infinitive expresses liking an activity. Le is formal to you here.', 'Describe an interest and ask a related question.', 'Mi ___ leggere la sera.', 'piace'],
  ['Offering help', 'Oggi ha molto lavoro. Posso aiutarla dopo pranzo. Da dove vuole cominciare?', 'You have a lot of work today. I can help you after lunch. Where would you like to start?', 'Posso plus an infinitive expresses ability or an offer. Aiutarla uses formal la for you.', 'Offer help with a task.', '___ aiutarla dopo pranzo.', 'Posso'],
  ['Expressing a preference', 'Preferisco lavorare in un posto tranquillo. La musica a volte mi distrae. Ma ognuno ha le proprie abitudini.', 'I prefer working in a quiet place. Music sometimes distracts me. But everyone has their own habits.', 'Preferisco plus an infinitive states a preference. Ma introduces a contrast.', 'Explain a preference respectfully.', '___ lavorare in un posto tranquillo.', 'Preferisco'],
  ['Weekend plans', 'Questo fine settimana vedrò degli amici. Cucineremo insieme. Se farà bel tempo, mangeremo fuori.', 'This weekend I will see some friends. We will cook together. If the weather is nice, we will eat outside.', 'Vedrò, cucineremo, and mangeremo are future forms. Insieme means together.', 'Write about a weekend plan.', 'Cucineremo ___ .', 'insieme'],
];
